follow_xdistance= 20;
follow_ydistance = -900;
follow_speed=.15;
player_reference =noone;
bob_timer=0;
bob_speed=.08;
bob_amount=20;
laser_ready=true
is_attacking=false;
target=noone;
upgrade=false;
sound=audio_play_sound(snd_drone_hover,0,true);
using_upgrade_sound = false;